### PR TITLE
Fixing circleci exit code issue

### PR DESCRIPTION
**Pull request by zahid-arbisoft**
Fixing Circleci exit code issue
Fixing 1 failing mandrill client test

Note: Circleci is failing because of two failed tests, which are fixed in another PR

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/591/workflows/workflows_id/jobs/591/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/596/workflows/workflows_id/jobs/596/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/597/workflows/workflows_id/jobs/597/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/student/tests/test_helpers.py (100%)
openedx/adg/lms/student/views.py (0.0%): Missing lines 1-5
-------------
Total:   12 lines
Missing: 5 lines
Coverage: 58%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/598/workflows/workflows_id/jobs/598/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py (100%)
openedx/adg/common/mailchimp_pipeline/tests/test_tasks.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
openedx/adg/lms/student/views.py (0.0%): Missing lines 1-5
-------------
Total:   15 lines
Missing: 5 lines
Coverage: 66%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/599/workflows/workflows_id/jobs/599/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py (100%)
openedx/adg/common/mailchimp_pipeline/tests/test_tasks.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
openedx/adg/lms/student/views.py (0.0%): Missing lines 1-5
-------------
Total:   15 lines
Missing: 5 lines
Coverage: 66%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/606/workflows/workflows_id/jobs/606/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py (100%)
openedx/adg/common/mailchimp_pipeline/tests/test_tasks.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   10 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/608/workflows/workflows_id/jobs/608/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   9 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/609/workflows/workflows_id/jobs/609/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   9 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/612/workflows/workflows_id/jobs/612/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/tests/test_helpers.py (100%)
openedx/adg/common/mailchimp_pipeline/tests/test_tasks.py (100%)
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   10 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍

**Review by muak50 — APPROVED** [review]
LGTM 👍

**Pull request merged**
