### PR TITLE
LP-2439

### PR DESCRIPTION
**Pull request by asadali145**

### CODE REVIEW

**Review by aliassad — DISMISSED** [review]
LGTM 👍

**Comment by aliassad** [comment]
> **pylint:** ❌
> **pycodestyle:** ✔️
> **iSort:** ❌
> 
> **Please fix following pylint issues:**
> 
> ```
> ************* Module edx-platform.openedx.core.djangoapps.user_authn.views.login_form
> openedx/core/djangoapps/user_authn/views/login_form.py:154:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> ************* Module edx-platform.openedx.core.djangoapps.user_authn.views.register
> openedx/core/djangoapps/user_authn/views/register.py:465:15: R5102: Instead of HttpResponse(content_type='application/json') use JsonResponse() (http-response-with-content-type-json)
> openedx/core/djangoapps/user_authn/views/register.py:566:27: R1704: Redefining argument with the local name 'errors' (redefined-argument-from-local)
> openedx/core/djangoapps/user_authn/views/register.py:577:12: W0107: Unnecessary pass statement (unnecessary-pass)
> openedx/core/djangoapps/user_authn/views/register.py:451:0: I0021: Useless suppression of 'missing-class-docstring' (useless-suppression)
> openedx/core/djangoapps/user_authn/views/register.py:503:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> openedx/core/djangoapps/user_authn/views/register.py:451:0: I0021: Useless suppression of 'missing-module-docstring' (useless-suppression)
> ************* Module edx-platform.openedx.core.djangoapps.user_authn.views.tests.test_register
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:596:31: R1719: The if expression can be replaced with 'test' (simplifiable-if-expression)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1966:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1967:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1968:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1969:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1970:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1984:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1985:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1986:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1987:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:1988:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:2041:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:2019:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> openedx/core/djangoapps/user_authn/views/tests/test_register.py:2023:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> 
> -----------------------------------
> Your code has been rated at 9.84/10
> ```
> 
> **Please fix following iSort issues:**
> 
> ```
>  ERROR: /openedx/core/djangoapps/user_authn/views/register.py Imports are incorrectly sorted.
> ERROR: /openedx/core/djangoapps/user_authn/views/tests/test_register.py Imports are incorrectly sorted. 
> ```

Did solving pylint errors were not in this scope ?

**Comment by asadali145** [comment]
> > **pylint:** ❌
> > **pycodestyle:** ✔️
> > **iSort:** ❌
> > **Please fix following pylint issues:**
> > ```
> > ************* Module edx-platform.openedx.core.djangoapps.user_authn.views.login_form
> > openedx/core/djangoapps/user_authn/views/login_form.py:154:4: R1702: Too many nested blocks (6/5) (too-many-nested-blocks)
> > ************* Module edx-platform.openedx.core.djangoapps.user_authn.views.register
> > openedx/core/djangoapps/user_authn/views/register.py:465:15: R5102: Instead of HttpResponse(content_type='application/json') use JsonResponse() (http-response-with-content-type-json)
> > openedx/core/djangoapps/user_authn/views/register.py:566:27: R1704: Redefining argument with the local name 'errors' (redefined-argument-from-local)
> > openedx/core/djangoapps/user_authn/views/register.py:577:12: W0107: Unnecessary pass statement (unnecessary-pass)
> > openedx/core/djangoapps/user_authn/views/register.py:451:0: I0021: Useless suppression of 'missing-class-docstring' (useless-suppression)
> > openedx/core/djangoapps/user_authn/views/register.py:503:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> > openedx/core/djangoapps/user_authn/views/register.py:451:0: I0021: Useless suppression of 'missing-module-docstring' (useless-suppression)
> > ************* Module edx-platform.openedx.core.djangoapps.user_authn.views.tests.test_register
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:596:31: R1719: The if expression can be replaced with 'test' (simplifiable-if-expression)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1966:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1967:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1968:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1969:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1970:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1984:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1985:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1986:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1987:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:1988:0: R1721: Unnecessary use of a comprehension (unnecessary-comprehension)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:2041:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:2019:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> > openedx/core/djangoapps/user_authn/views/tests/test_register.py:2023:0: I0021: Useless suppression of 'no-member' (useless-suppression)
> > 
> > -----------------------------------
> > Your code has been rated at 9.84/10
> > ```
> > 
> > 
> > **Please fix following iSort issues:**
> > ```
> >  ERROR: /openedx/core/djangoapps/user_authn/views/register.py Imports are incorrectly sorted.
> > ERROR: /openedx/core/djangoapps/user_authn/views/tests/test_register.py Imports are incorrectly sorted. 
> > ```
> 
> Did solving pylint errors were not in this scope ?

These are due to core code. Not because of my changes.

**Review by aliassad — APPROVED** [review]
LGTM 👍

**Comment by zahid-arbisoft** [comment]
Please add proper title of PR and add story link in desc

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/455/workflows/workflows_id/jobs/455/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/registration_extension/admin.py (100%)
openedx/adg/lms/registration_extension/apps.py (0.0%): Missing lines 4,7-8
openedx/adg/lms/registration_extension/constants.py (100%)
openedx/adg/lms/registration_extension/forms.py (83.3%): Missing lines 35-36,57-58,60
openedx/adg/lms/registration_extension/migrations/0001_initial.py (100%)
openedx/adg/lms/registration_extension/models.py (100%)
openedx/core/djangoapps/user_authn/views/login_form.py (100%)
openedx/core/djangoapps/user_authn/views/register.py (100%)
openedx/core/djangoapps/user_authn/views/tests/test_register.py (100%)
-------------
Total:   62 lines
Missing: 8 lines
Coverage: 87%
-------------
```

**Review by ahmed-faraz46 — APPROVED** [review]

**Pull request merged**
