### PR TITLE
LP-2801 Stop syncing user attributes with Mailchimp

### PR DESCRIPTION
**Pull request by annas-usman**
[Ticket](https://philanthropyu.atlassian.net/browse/LP-2801)

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2403/workflows/workflows_id/jobs/2403/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/handlers.py (100%)
-------------
Total:   1 line
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by AliAdnanSohail — APPROVED** [review]

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2408/workflows/workflows_id/jobs/2408/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/apps.py (66.7%): Missing lines 21
openedx/adg/common/mailchimp_pipeline/tests/test_handlers.py (100%)
-------------
Total:   11 lines
Missing: 1 line
Coverage: 90%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2410/workflows/workflows_id/jobs/2410/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by MunamMubashir-arbisoft — APPROVED** [review]

**Review by harris-irfan — APPROVED** [review]
Thank you for being extra flexible during the development of this ticket. We initially started from from an unclean way and eventually landed at the best possible approach for this ticket. 👍

**Pull request merged**
