### PR TITLE
LP-2439 migration choices issue

### PR DESCRIPTION
**Pull request by asadali145**
Migration issue detected by unit tests and fixed that

### CODE REVIEW

**Review by ahmed-faraz46 — APPROVED** [review]
LGTM 👍

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/452/workflows/workflows_id/jobs/452/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/registration_extension/constants.py (100%)
-------------
Total:   1 line
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by aliassad — APPROVED** [review]
LGTM 👍

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/453/workflows/workflows_id/jobs/453/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/registration_extension/constants.py (100%)
-------------
Total:   1 line
Missing: 0 lines
Coverage: 100%
-------------
```

**Pull request merged**
