### PR TITLE
LP-2600 Add model for webinar event

### PR DESCRIPTION
**Pull request by javeriaejaz-arbisoft**

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1430/workflows/workflows_id/jobs/1430/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/__init__.py (100%)
openedx/adg/lms/webinars/admin.py (81.8%): Missing lines 26-27,29-30
openedx/adg/lms/webinars/apps.py (100%)
openedx/adg/lms/webinars/constants.py (100%)
openedx/adg/lms/webinars/migrations/0001_initial.py (0.0%): Missing lines 3-8,11,13,15,19
openedx/adg/lms/webinars/models.py (83.0%): Missing lines 75,78-83,103
-------------
Total:   85 lines
Missing: 22 lines
Coverage: 74%
-------------
```

**Comment by javeriaejaz-arbisoft** [comment]
The coverage is below 80% because of the added migrations file.

**Comment by harris-irfan** [comment]
> The coverage is below 80% because of the added migrations file.

@zahid-arbisoft can we make sure that migration files are not included in the coverage report?

**Review by harris-irfan — APPROVED** [review]

**Comment by zahid-arbisoft** [comment]
> > The coverage is below 80% because of the added migrations file.
> 
> @zahid-arbisoft can we make sure that migration files are not included in the coverage report?

I had a brief discussion with @javeriaejaz-arbisoft today, I think we should create a separate story of this.

**Pull request merged**
