### PR TITLE
LP-2473 - Create GitHub actions to automate translations flow

### PR DESCRIPTION
**Pull request by MunamMubashir-arbisoft**
Ticket: [LP-2473](https://philanthropyu.atlassian.net/browse/LP-2473)

Create github action to automate the translations flow by doing the following:

1. Install all dependencies.
2. Clone `adg-edx-theme` inside the repo in the _themes_ directory.
3. Checkout the feature branch in both the repos i.e `edx-platform` and `adg-edx-theme`.
4. Generate all the translations as described [here](https://github.com/OmnipreneurshipAcademy/devstack/blob/master/docs/adg/transifex_translations.rst).
5. Commit and push the changed translation files in the feature branch.
6. Push the changed translations to Transifex by `tx push` command.

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/901/workflows/workflows_id/jobs/901/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by zahid-arbisoft — CHANGES_REQUESTED** [review]

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/918/workflows/workflows_id/jobs/918/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by zahid-arbisoft — APPROVED** [review]

**Review by zeshanarifios — APPROVED** [review]
LGTM 👍

**Review by RanaWaqar7550 — APPROVED** [review]
LGTM

**Pull request merged**
