### PR TITLE
LP-2629 Customise interface for webinar for admins

### PR DESCRIPTION
**Pull request by aliassad**
[LP-2629](https://philanthropyu.atlassian.net/browse/LP-2629)
[adg-theme-PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/206)

Notes:
- Update presenter, co-hosts and panelists fields for model admin i.e. use raw_id_fields.
- Save as new button text is changed to Clone  for webinars
- Handle status of a webinar. Status should be marked as upcoming for cloned webinars.

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1456/workflows/workflows_id/jobs/1456/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/admin.py (33.3%): Missing lines 34-37
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/factories.py (100%)
openedx/adg/lms/webinars/tests/test_models.py (100%)
-------------
Total:   73 lines
Missing: 4 lines
Coverage: 94%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1457/workflows/workflows_id/jobs/1457/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/admin.py (33.3%): Missing lines 34-37
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/factories.py (100%)
openedx/adg/lms/webinars/tests/test_models.py (100%)
-------------
Total:   73 lines
Missing: 4 lines
Coverage: 94%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1460/workflows/workflows_id/jobs/1460/artifacts)**. Coverage !!! :scream:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/admin.py (33.3%): Missing lines 34-37
-------------
Total:   6 lines
Missing: 4 lines
Coverage: 33%
-------------
```

**Review by asadali145 — APPROVED** [review]
LGTM

**Review by zahid-arbisoft — APPROVED** [review]

**Pull request merged**
