### PR TITLE
translations updated for new designs of home and about us pages

### PR DESCRIPTION
**Pull request by adeelaarbi**
[LP-XXXX](https://philanthropyu.atlassian.net/browse/LP-XXXX)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/###)

***

#### Description:
Add a description of your changes here.

***

## Things to Cross-check:

- [ ] Technical Docs updated if needed?
- [ ] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [ ] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Review by ihtram — DISMISSED** [review]
LGTM, some check are failing which we need fix in next PR

**Comment by adeelaarbi** [comment]
circleci config updated and translations for new home and about pages added

**Review by ihtram — APPROVED** [review]
Looks Good

**Comment by adeelaarbi** [comment]
[circleci config updated, memcache updated to use md5 and translations for homepage and about us page added

**Pull request merged**
