### PR TITLE
LP-2617 - Send cancellation emails for cohosts, panelists and presenter

### PR DESCRIPTION
**Pull request by MunamMubashir-arbisoft**
[LP-2617](https://philanthropyu.atlassian.net/browse/LP-2617)

- Send emails to the presenter, panelists, and co-hosts in addition to the registered users.
- Make sure an email address gets only a single email per cancellation.
- Add/Modify unit tests to cover all the edge cases.

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1482/workflows/workflows_id/jobs/1482/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/helpers.py (100%)
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/test_helpers.py (100%)
-------------
Total:   24 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by zahid-arbisoft — APPROVED** [review]

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1486/workflows/workflows_id/jobs/1486/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/helpers.py (100%)
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/test_helpers.py (100%)
-------------
Total:   34 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by javeriaejaz-arbisoft — APPROVED** [review]
LGTM

**Review by ahmed-faraz46 — APPROVED** [review]
Nicely implemented, Well tested :+1:

**Pull request merged**
