### PR TITLE
LP-2371 Implement and Integrate Application review

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2371](https://philanthropyu.atlassian.net/browse/LP-2371)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/457)

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2725/workflows/workflows_id/jobs/2725/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/api/permissions.py (100%)
openedx/adg/admin_dashboard/applications/api/serializers.py (100%)
openedx/adg/admin_dashboard/applications/api/tests/constants.py (100%)
openedx/adg/admin_dashboard/applications/api/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/api/urls.py (100%)
openedx/adg/admin_dashboard/applications/api/views.py (100%)
openedx/adg/admin_dashboard/applications/constants.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/mixins.py (95.7%): Missing lines 52,86
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/urls.py (100%)
openedx/adg/admin_dashboard/applications/views.py (97.2%): Missing lines 234,237
openedx/adg/common/helpers.py (100%)
openedx/adg/common/tests/test_helpers.py (100%)
openedx/adg/conftest.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
-------------
Total:   378 lines
Missing: 4 lines
Coverage: 98%
-------------
```

**Review by harris-irfan — DISMISSED** [review]
Conflicts in translation files need to be resolved by merging latest master into the feature branch.

**Review by harris-irfan — APPROVED** [review]

**Comment by asadali145** [comment]
Merging this as the unit tests are already successful.

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2728/workflows/workflows_id/jobs/2728/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/api/permissions.py (100%)
openedx/adg/admin_dashboard/applications/api/serializers.py (100%)
openedx/adg/admin_dashboard/applications/api/tests/constants.py (100%)
openedx/adg/admin_dashboard/applications/api/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/api/urls.py (100%)
openedx/adg/admin_dashboard/applications/api/views.py (100%)
openedx/adg/admin_dashboard/applications/constants.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/mixins.py (95.7%): Missing lines 52,86
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_views.py (100%)
openedx/adg/admin_dashboard/applications/urls.py (100%)
openedx/adg/admin_dashboard/applications/views.py (97.2%): Missing lines 234,237
openedx/adg/common/helpers.py (100%)
openedx/adg/common/tests/test_helpers.py (100%)
openedx/adg/conftest.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
-------------
Total:   378 lines
Missing: 4 lines
Coverage: 98%
-------------
```

**Pull request merged**
