### PR TITLE
LP-2613 Fix requirements for py2neo

### PR DESCRIPTION
**Pull request by zahid-arbisoft**
[LP-2613](https://philanthropyu.atlassian.net/browse/LP-2613) Fix requirements for py2neo

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1392/workflows/workflows_id/jobs/1392/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1393/workflows/workflows_id/jobs/1393/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by asadali145 — APPROVED** [review]
LGTM

**Review by ahmed-faraz46 — APPROVED** [review]

**Comment by ahmed-faraz46** [comment]
@zahid-arbisoft let's please document the core changes if we haven't already

**Comment by zahid-arbisoft** [comment]
Logged core change in [wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes#18-updating-py2neo-package-in-requrement-files-lp-2613)

**Pull request merged**
