### PR TITLE
LP-2972 Show pop-up on enrolment

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2972](https://philanthropyu.atlassian.net/browse/LP-2972)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/682)

***

#### Description:

- Unenroll from all other enrolled versions when a user tries to enroll in a new one.
- Show pop-up In the above case.
- Show a message when enroll button is disabled, in case a certificate for one of the versions is generated.
- Update old tests and add new ones.

***

## Things to Cross-check:

- [x] Technical Docs updated if needed?
- [x] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [ ] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3548/workflows/workflows_id/jobs/3548/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/test_models.py (90.9%): Missing lines 759-760
openedx/adg/lms/courseware_override/helpers.py (83.3%): Missing lines 112,117-118
openedx/adg/lms/courseware_override/tests/test_helpers.py (100%)
-------------
Total:   57 lines
Missing: 5 lines
Coverage: 91%
-------------
```

**Comment by asadali145** [comment]
Quality workflow is failing for core file.

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Review by javeriaejaz-arbisoft — APPROVED** [review]

**Pull request merged**
