### PR TITLE
LP-2662 Added support site url

### PR DESCRIPTION
**Pull request by asadali145**

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1788/workflows/workflows_id/jobs/1788/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/student/helpers.py (83.3%): Missing lines 176-177
openedx/adg/lms/student/tests/test_helpers.py (100%)
-------------
Total:   22 lines
Missing: 2 lines
Coverage: 90%
-------------
```

**Review by aliassad — APPROVED** [review]
LGTM 👍

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1792/workflows/workflows_id/jobs/1792/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by MunamMubashir-arbisoft — APPROVED** [review]
LGTM

**Pull request merged**
