### PR TITLE
LP-2974 Redirect to FAQs as per the platform language

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2974](https://philanthropyu.atlassian.net/browse/LP-2974)

***

#### Description:

- Redirect to FAQs as per the platform language
***

## Things to Cross-check:

- [ ] Technical Docs updated if needed?
- [ ] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [ ] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by aightmunam — APPROVED** [review]

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3515/workflows/workflows_id/jobs/3515/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by emraan004 — DISMISSED** [review]
Looks good to me 👍

**Review by javeriaejaz-arbisoft — APPROVED** [review]

**Comment by asadali145** [comment]
Sorry for bothering again, fixed an import that caused the quality workflow failure. It wasn't a change in this PR but I have fixed it.

**Review by emraan004 — APPROVED** [review]
👍

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3516/workflows/workflows_id/jobs/3516/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/branding_extension/constants.py (100%)
openedx/adg/lms/branding_extension/helpers.py (100%)
openedx/adg/lms/certificates_override/helpers.py (100%)
openedx/adg/lms/certificates_override/tests/test_helpers.py (100%)
openedx/adg/lms/constants.py (100%)
-------------
Total:   12 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Pull request merged**
