### PR TITLE
LP-2994 Use `strftime_localized` to translate date strings

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2994](https://philanthropyu.atlassian.net/browse/LP-2994)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/700)

***

#### Description:

- Use `strftime_localized` in place of builtin strftime to translate date strings

***

## Things to Cross-check:

- [x] Technical Docs updated if needed?
- [x] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [x] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3739/workflows/workflows_id/jobs/3739/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3739/workflows/workflows_id/jobs/3739/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3739/workflows/workflows_id/jobs/3739/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3739/workflows/workflows_id/jobs/3739/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3739/workflows/workflows_id/jobs/3739/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3739/workflows/workflows_id/jobs/3739/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   8 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3747/workflows/workflows_id/jobs/3747/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3748/workflows/workflows_id/jobs/3748/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3752/workflows/workflows_id/jobs/3752/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/common/helpers.py (100%)
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/helpers.py (100%)
openedx/adg/lms/student/views.py (100%)
-------------
Total:   11 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by asadali145** [comment]
Please ignore code quality workflow as it is failing for a core file.

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]
LGTM

**Pull request merged**
