### PR TITLE
LP-2619 Pass dict of webinar object to celery task

### PR DESCRIPTION
**Pull request by asadali145**

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1653/workflows/workflows_id/jobs/1653/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/admin.py (100%)
openedx/adg/lms/webinars/constants.py (100%)
openedx/adg/lms/webinars/helpers.py (87.5%): Missing lines 124
openedx/adg/lms/webinars/models.py (75.0%): Missing lines 165
openedx/adg/lms/webinars/tasks.py (100%)
openedx/adg/lms/webinars/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_tasks.py (100%)
openedx/adg/lms/webinars/views.py (100%)
-------------
Total:   20 lines
Missing: 2 lines
Coverage: 90%
-------------
```

**Review by annas-usman — APPROVED** [review]
LGTM

**Review by harris-irfan — APPROVED** [review]

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1655/workflows/workflows_id/jobs/1655/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1656/workflows/workflows_id/jobs/1656/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Pull request merged**
