### PR TITLE
LP-2981 Fix date issues

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2981](https://philanthropyu.atlassian.net/browse/LP-2981)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/686)

***

#### Description:

- Fix issues in tests and admin dashboard related to date

***

## Things to Cross-check:

- [ ] Technical Docs updated if needed?
- [ ] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [ ] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3557/workflows/workflows_id/jobs/3557/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/applications/helpers.py (100%)
openedx/adg/admin_dashboard/applications/tests/test_helpers.py (100%)
-------------
Total:   4 lines
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by aightmunam — APPROVED** [review]
LGTM!

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Pull request merged**
