### PR TITLE
LP-2620 Add backend functionality to register & cancel webinar

### PR DESCRIPTION
**Pull request by zahid-arbisoft**
[LP-2620](https://philanthropyu.atlassian.net/browse/LP-2620) Add backend functionality to register & cancel webinar

### CODE REVIEW

**Review by MunamMubashir-arbisoft — APPROVED** [review]
LGTM!

**Review by MunamMubashir-arbisoft — DISMISSED** [review]

**Review by muak50 — APPROVED** [review]
LGTM 👍

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1532/workflows/workflows_id/jobs/1532/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/common/lib/mandrill_client/client.py (100%)
openedx/adg/lms/urls.py (100%)
openedx/adg/lms/webinars/helpers.py (100%)
openedx/adg/lms/webinars/migrations/0003_auto_20210414_1532.py (0.0%): Missing lines 3-4,7,9,14
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/test_helpers.py (100%)
openedx/adg/lms/webinars/tests/test_views.py (100%)
openedx/adg/lms/webinars/urls.py (100%)
openedx/adg/lms/webinars/views.py (96.2%): Missing lines 20
-------------
Total:   88 lines
Missing: 6 lines
Coverage: 93%
-------------
```

**Review by MunamMubashir-arbisoft — APPROVED** [review]
LGTM!

**Pull request merged**
