### PR TITLE
LP-2835 Integrate Admin Accounts

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2835](https://philanthropyu.atlassian.net/browse/LP-2835)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/497)

***

#### Description:
Integrated Admin Accounts list view
Added new link for pending invites in settings dashboard
Integrated links for settings dashboard
Integrated pending invites page

### CODE REVIEW

**Comment by asadali145** [comment]
Will take pull from master once tests are complete and then we will not wait for tests again.

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2823/workflows/workflows_id/jobs/2823/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/constants.py (100%)
openedx/adg/admin_dashboard/admin_settings/migrations/0002_auto_20210908_1425.py (0.0%): Missing lines 3,6,8,12
openedx/adg/admin_dashboard/admin_settings/models.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/constants.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/factories.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/test_views.py (100%)
openedx/adg/admin_dashboard/admin_settings/urls.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
-------------
Total:   123 lines
Missing: 4 lines
Coverage: 96%
-------------
```

**Review by annas-usman — APPROVED** [review]

**Comment by asadali145** [comment]
Tests are already completed.

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2827/workflows/workflows_id/jobs/2827/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/constants.py (100%)
openedx/adg/admin_dashboard/admin_settings/migrations/0002_auto_20210908_1425.py (0.0%): Missing lines 3,6,8,12
openedx/adg/admin_dashboard/admin_settings/models.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/constants.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/factories.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/tests/test_views.py (100%)
openedx/adg/admin_dashboard/admin_settings/urls.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
-------------
Total:   123 lines
Missing: 4 lines
Coverage: 96%
-------------
```

**Pull request merged**
