### PR TITLE
LP-2966 Fix business line translations, redirect to new account settings page

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2966](https://philanthropyu.atlassian.net/browse/LP-2966)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/###)

***

#### Description:
Add a description of your changes here.

***

## Things to Cross-check:

- [ ] Technical Docs updated if needed?
- [ ] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [ ] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Review by Syed-Ali-Abbas-Zaidi — APPROVED** [review]

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3489/workflows/workflows_id/jobs/3489/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/helpers.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (100%)
openedx/adg/lms/applications/forms.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (90.9%): Missing lines 257
openedx/adg/lms/student/tests/test_views.py (100%)
openedx/adg/lms/urls.py (100%)
-------------
Total:   33 lines
Missing: 1 line
Coverage: 96%
-------------
```

**Review by faizan-philu — APPROVED** [review]

**Review by javeriaejaz-arbisoft — APPROVED** [review]

**Pull request merged**
