### PR TITLE
LP-2670 - Fix Webinar issues

### PR DESCRIPTION
**Pull request by MunamMubashir-arbisoft**
[LP-2670](https://philanthropyu.atlassian.net/browse/LP-2670)

- Add restriction on webinar `title` field
- Remove `virtual` field and make `meeting_url` field required
- Fix the search functionality in webinar registrations
- Add User model as read-only in ADG admin to fix user related field lookup
- Add unit tests for all the added code

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1782/workflows/workflows_id/jobs/1782/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/admin.py (100%)
openedx/adg/lms/webinars/migrations/0005_auto_20210503_1311.py (0.0%): Missing lines 3,6,8,12
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/factories.py (100%)
openedx/adg/lms/webinars/tests/test_admin.py (100%)
-------------
Total:   39 lines
Missing: 4 lines
Coverage: 89%
-------------
```

**Review by ahmed-faraz46 — APPROVED** [review]

**Comment by ahmed-faraz46** [comment]
Tests were [already run successfully](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1757/workflows/feb6977f-782f-4bb4-aa14-167fa94d39d1/jobs/1782), so merging the PR.

**Comment by MunamMubashir-arbisoft** [comment]
The circle ci tests for LP-2670 have already [run successfully](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1757/workflows/feb6977f-782f-4bb4-aa14-167fa94d39d1/jobs/1782) without any failures.
Upon adding updated translations, the tests were all re-run. I, therefore, asked @ahmed-faraz46 to override them and got the ticket merged.

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1819/workflows/workflows_id/jobs/1819/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/webinars/admin.py (100%)
openedx/adg/lms/webinars/migrations/0005_auto_20210503_1311.py (0.0%): Missing lines 3,6,8,12
openedx/adg/lms/webinars/models.py (100%)
openedx/adg/lms/webinars/tests/factories.py (100%)
openedx/adg/lms/webinars/tests/test_admin.py (100%)
-------------
Total:   39 lines
Missing: 4 lines
Coverage: 89%
-------------
```

**Pull request merged**
