### PR TITLE
LP-2585 Export philu personal access token in environment

### PR DESCRIPTION
**Pull request by ahmed-faraz46**
[LP-2585](https://philanthropyu.atlassian.net/browse/LP-2585)
- Export philu personal access token in environment
NOTE: For CircleCI workflow, PHILU_PAT is exported in environment, from the app, so no code change was required, Right now pipelines might post that no python file detected, but I've tested it with some temporary changes and reverted those changes, attaching screen shots of successful runs
Screen Shot 2021-03-18 at 10 25 56 PM

### CODE REVIEW

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1302/workflows/workflows_id/jobs/1302/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1336/workflows/workflows_id/jobs/1336/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/common/mailchimp_pipeline/handlers.py (100%)
-------------
Total:   1 line
Missing: 0 lines
Coverage: 100%
-------------
```

**Comment by zahid-arbisoft** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1337/workflows/workflows_id/jobs/1337/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by emraan004 — APPROVED** [review]
LGTM 👍

**Review by asadali145 — APPROVED** [review]

**Pull request merged**
