### PR TITLE
Add is business unit pre req completed field in application hub

### PR DESCRIPTION
**Pull request by ahmed-faraz46**
NOTE: Didn't rename any existing field to keep the spirit of this ticket, that would be done if required in the relevant tickets.

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1956/workflows/workflows_id/jobs/1956/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/models.py (100%)
-------------
Total:   1 line
Missing: 0 lines
Coverage: 100%
-------------
```

**Review by MunamMubashir-arbisoft — APPROVED** [review]
Looks good to me!

**Review by annas-usman — CHANGES_REQUESTED** [review]
There is a methods `are_application_pre_reqs_completed`, we should update that.

**Comment by ahmed-faraz46** [comment]
> There is a method `are_application_pre_reqs_completed`, we should update that.

@annas-usman how about updating this or any other method in their relevant tickets? because if we will update this method we would have to update the unit test and then we would have to get it tested from the QA team too, so we might lose the spirit of creating a separate ticket for adding a field.

**Review by annas-usman — APPROVED** [review]

**Pull request merged**
