### PR TITLE
LP-2662 Added support site url

### PR DESCRIPTION
**Pull request by asadali145**

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1797/workflows/workflows_id/jobs/1797/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Review by aliassad — DISMISSED** [review]
LGTM 👍

**Comment by asadali145** [comment]
Rebasing it from master to get the latest translations. Tests are successful, Just the translation files are showing conflicts.

**Review by aliassad — DISMISSED** [review]
LGTM 👍

**Review by MunamMubashir-arbisoft — DISMISSED** [review]

**Review by MunamMubashir-arbisoft — APPROVED** [review]

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - Edx
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/1831/workflows/workflows_id/jobs/1831/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/master...HEAD, staged and unstaged changes
-------------
No lines with coverage information in this diff.
-------------
```

**Pull request merged**
