### PR TITLE
LP-2886 Add middleware for checking admin dashboard access

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2886](https://philanthropyu.atlassian.net/browse/LP-2886)

***

#### Description:
Added middleware to check admin permissions and removed usage of `EnsureAdminUserAuthenticatedMixin` with each view.

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2902/workflows/workflows_id/jobs/2902/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/admin_settings/urls.py (100%)
openedx/adg/admin_dashboard/admin_settings/views.py (100%)
openedx/adg/admin_dashboard/applications/views.py (100%)
openedx/adg/admin_dashboard/middleware.py (92.9%): Missing lines 29
openedx/adg/admin_dashboard/performance/views.py (100%)
openedx/adg/admin_dashboard/webinars/api/tests/test_api_views.py (100%)
openedx/adg/admin_dashboard/webinars/constants.py (100%)
openedx/adg/admin_dashboard/webinars/forms.py (81.9%): Missing lines 66-67,103-105,107-110,112-113,139,142
openedx/adg/admin_dashboard/webinars/helpers.py (100%)
openedx/adg/admin_dashboard/webinars/tests/conftest.py (100%)
openedx/adg/admin_dashboard/webinars/tests/test_forms.py (100%)
openedx/adg/admin_dashboard/webinars/tests/test_helpers.py (100%)
openedx/adg/admin_dashboard/webinars/urls.py (100%)
openedx/adg/admin_dashboard/webinars/views.py (83.3%): Missing lines 115-117
openedx/adg/common/lib/zoom_client/client.py (42.9%): Missing lines 20,32-34,46-48,61-63,67-69,81-83
openedx/adg/conftest.py (100%)
openedx/adg/lms/utils/date_utils.py (100%)
openedx/adg/lms/utils/tests/tests_date_utils.py (100%)
openedx/adg/lms/webinars/constants.py (100%)
openedx/adg/lms/webinars/models.py (77.8%): Missing lines 421,457
openedx/adg/lms/webinars/tests/factories.py (100%)
openedx/adg/lms/webinars/tests/test_models.py (100%)
-------------
Total:   275 lines
Missing: 35 lines
Coverage: 87%
-------------
```

**Comment by asadali145** [comment]
Pls ignore the workflows, I cancelled 2 as I mistakenly created PR against master then switched to develop.

**Review by annas-usman — APPROVED** [review]
LGTM

**Review by AliAdnanSohail — APPROVED** [review]

**Comment by asadali145** [comment]
@emraan004 bhai suggested that this is not a better approach as it will always check request path for all the requests so we should use the mixin as we are using. Closing this one.

**Pull request closed without merging**
