### PR TITLE
Refresh Develop

### PR DESCRIPTION
**Pull request by javeriaejaz-arbisoft**

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2492/workflows/workflows_id/jobs/2492/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/performance/constants.py (100%)
openedx/adg/admin_dashboard/performance/tests/test_views.py (100%)
openedx/adg/admin_dashboard/performance/urls.py (100%)
openedx/adg/admin_dashboard/performance/views.py (78.3%): Missing lines 211,213,215,217,226,236-237,239,241-242
openedx/adg/conftest.py (100%)
openedx/adg/constants.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_bu_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   206 lines
Missing: 10 lines
Coverage: 95%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2491/workflows/workflows_id/jobs/2491/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/performance/constants.py (100%)
openedx/adg/admin_dashboard/performance/tests/test_views.py (100%)
openedx/adg/admin_dashboard/performance/urls.py (100%)
openedx/adg/admin_dashboard/performance/views.py (78.3%): Missing lines 211,213,215,217,226,236-237,239,241-242
openedx/adg/conftest.py (100%)
openedx/adg/constants.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_bu_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
-------------
Total:   206 lines
Missing: 10 lines
Coverage: 95%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2496/workflows/workflows_id/jobs/2496/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/performance/constants.py (100%)
openedx/adg/admin_dashboard/performance/tests/test_views.py (100%)
openedx/adg/admin_dashboard/performance/urls.py (100%)
openedx/adg/admin_dashboard/performance/views.py (78.3%): Missing lines 211,213,215,217,226,236-237,239,241-242
openedx/adg/conftest.py (100%)
openedx/adg/constants.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_bu_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/our_team/models.py (100%)
-------------
Total:   209 lines
Missing: 10 lines
Coverage: 95%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/2495/workflows/workflows_id/jobs/2495/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/admin_dashboard/performance/constants.py (100%)
openedx/adg/admin_dashboard/performance/tests/test_views.py (100%)
openedx/adg/admin_dashboard/performance/urls.py (100%)
openedx/adg/admin_dashboard/performance/views.py (78.3%): Missing lines 211,213,215,217,226,236-237,239,241-242
openedx/adg/conftest.py (100%)
openedx/adg/constants.py (100%)
openedx/adg/lms/applications/admin.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_bu_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/management/commands/tests/test_update_is_prerequisite_courses_passed.py (100%)
openedx/adg/lms/applications/managers.py (100%)
openedx/adg/lms/applications/models.py (100%)
openedx/adg/lms/applications/tests/factories.py (100%)
openedx/adg/lms/applications/tests/test_admin/test_user_application_adg_admin.py (100%)
openedx/adg/lms/applications/tests/test_helpers.py (100%)
openedx/adg/lms/applications/tests/test_models.py (100%)
openedx/adg/lms/our_team/models.py (100%)
-------------
Total:   209 lines
Missing: 10 lines
Coverage: 95%
-------------
```

**Review by annas-usman — APPROVED** [review]

**Review by harris-irfan — APPROVED** [review]

**Review by asadali145 — APPROVED** [review]

**Pull request merged**
