### PR TITLE
LP-2966 Fix zero division error in completion and courses on hub in ar lang

### PR DESCRIPTION
**Pull request by asadali145**
[LP-2966](https://philanthropyu.atlassian.net/browse/LP-2966)

[Theme PR](https://github.com/OmnipreneurshipAcademy/adg-edx-theme/pull/662)

***

#### Description:
Fix course card for Arabic
Fix zero division for course completion.

***

## Things to Cross-check:

- [x] Technical Docs updated if needed?
- [x] [Domain Model](https://drive.google.com/file/d/1iRSqxDQQMXl6JzLw9nZtq1yGshwMBLTn/view?usp=sharing) updated if needed?
- [x] [Core Changes Wiki](https://github.com/OmnipreneurshipAcademy/edx-platform/wiki/Core-Changes) updated if needed?

### CODE REVIEW

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3497/workflows/workflows_id/jobs/3497/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/courseware_override/helpers.py (0.0%): Missing lines 139
-------------
Total:   5 lines
Missing: 1 line
Coverage: 80%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3497/workflows/workflows_id/jobs/3497/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/courseware_override/helpers.py (0.0%): Missing lines 139
-------------
Total:   5 lines
Missing: 1 line
Coverage: 80%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3497/workflows/workflows_id/jobs/3497/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/courseware_override/helpers.py (0.0%): Missing lines 139
-------------
Total:   5 lines
Missing: 1 line
Coverage: 80%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3497/workflows/workflows_id/jobs/3497/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/courseware_override/helpers.py (0.0%): Missing lines 139
-------------
Total:   5 lines
Missing: 1 line
Coverage: 80%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3497/workflows/workflows_id/jobs/3497/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/courseware_override/helpers.py (0.0%): Missing lines 139
-------------
Total:   5 lines
Missing: 1 line
Coverage: 80%
-------------
```

**Comment by omnipreneurshipA** [comment]
## Diff Coverage Report - ADG
Check-out complete **[report](https://app.circleci.com/pipelines/github/OmnipreneurshipAcademy/edx-platform/3497/workflows/workflows_id/jobs/3497/artifacts)**. Coverage !!! :rocket:
```
-------------
Diff Coverage
Diff: origin/develop...HEAD, staged and unstaged changes
-------------
openedx/adg/lms/applications/helpers.py (100%)
openedx/adg/lms/courseware_override/helpers.py (0.0%): Missing lines 139
-------------
Total:   5 lines
Missing: 1 line
Coverage: 80%
-------------
```

**Review by AliAdnanSohail — APPROVED** [review]

**Comment by asadali145** [comment]
A random test failed, We can ignore.

**Pull request merged**
